#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Pati RSR local-reach applicability figure.

Each reach is bounded by two main-canal control/diversion nodes. The downstream
node stage generated by the Saint-Venant no-diversion forward model is used as
the RSR input boundary, and the upstream node stage is reconstructed through an
equivalent prismatic trapezoidal reach.
"""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Dict, List, Sequence

from PIL import Image, ImageDraw

import pati_local_equivalent_segment_89_71 as local89
import pati_real_main_canal_no_diversion as base


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "results" / "pati_local_reach_applicability_results"
FIG_DIR = OUT_DIR / "figures"

# tuple format: downstream node, upstream node
REACHES = [
    (89, 71),
    (150, 89),
    (194, 150),
    (287, 194),
    (349, 287),
    (383, 349),
    (456, 383),
]

FACTORS = [0.75, 1.00, 1.25, 1.50, 2.00, 3.00, 4.00]


def evaluate_reach(forward: Dict[str, object], downstream_node: int, upstream_node: int) -> Dict[str, object]:
    ids: List[int] = forward["ids"]  # type: ignore[assignment]
    x: List[float] = forward["x"]  # type: ignore[assignment]
    sections: List[base.stage1.SectionParam] = forward["sections"]  # type: ignore[assignment]
    times_h: List[float] = forward["times_h"]  # type: ignore[assignment]
    depth_t: List[List[float]] = forward["depth_nodes"]  # type: ignore[assignment]
    q_t: List[List[float]] = forward["q_nodes"]  # type: ignore[assignment]
    dt_seconds = (times_h[1] - times_h[0]) * 3600.0
    up_idx = ids.index(upstream_node)
    down_idx = ids.index(downstream_node)
    sec_eq, slope_eq, length_m = local89.equivalent_section(forward, up_idx, down_idx)

    y_down_real = [row[down_idx] for row in depth_t]
    y_up_obs = [row[up_idx] for row in depth_t]
    q_up_obs = [row[up_idx] for row in q_t]
    q_down_sv = [row[down_idx] for row in q_t]
    y_down_eq = local89.convert_real_depth_to_equivalent_depth(y_down_real, sections[down_idx], sec_eq)

    factor_rows: List[Dict[str, float]] = []
    best_row: Dict[str, float] | None = None
    for factor in FACTORS:
        rsr_cfg = base.RSRConfig(routing_celerity_factor=factor)
        y_up_eq, q_up_sim, _ = local89.reverse_one_equivalent_reach(
            y_down_eq,
            sec_eq,
            slope_eq,
            length_m,
            dt_seconds,
            rsr_cfg,
            initial_downstream_q=q_down_sv[0],
        )
        y_up_sim = local89.convert_equivalent_depth_to_real_depth(y_up_eq, sec_eq, sections[up_idx])
        row = local89.metric_dict(times_h, y_up_sim, y_up_obs, q_up_sim, q_up_obs, factor)
        factor_rows.append(row)
        if best_row is None or (row["depth_nse"] + 0.25 * row["q_nse"]) > (
            best_row["depth_nse"] + 0.25 * best_row["q_nse"]
        ):
            best_row = row

    assert best_row is not None
    default_row = next(r for r in factor_rows if abs(r["routing_celerity_factor"] - 1.5) < 1.0e-9)
    if best_row["depth_nse"] >= 0.50 and best_row["q_nse"] >= 0.50:
        level = "适用"
    elif best_row["depth_nse"] >= 0.50:
        level = "仅水深可参考"
    elif best_row["depth_nse"] >= 0.0:
        level = "弱适用"
    else:
        level = "不适用"
    return {
        "reach": f"{downstream_node}→{upstream_node}",
        "downstream_node": downstream_node,
        "upstream_node": upstream_node,
        "length_m": length_m,
        "slope_eq": slope_eq,
        "bottom_width_eq_m": sec_eq.bottom_width,
        "side_slope_eq": sec_eq.side_slope,
        "depth_eq_m": sec_eq.depth,
        "manning_eq": sec_eq.manning_n,
        "default_factor": default_row,
        "best_factor": best_row,
        "applicability": level,
        "factor_rows": factor_rows,
    }


def draw_applicability_figure(rows: Sequence[Dict[str, object]], path: Path):
    width, height = 1900, 1180
    img = Image.new("RGB", (width, height), "white")
    d = ImageDraw.Draw(img)
    title = base.get_font(42, True)
    font = base.get_font(24)
    small = base.get_font(19)
    tiny = base.get_font(17)
    d.text((80, 45), "Pati RSR 局部适用性分段评价图", font=title, fill="#162033")
    d.text(
        (80, 98),
        "下游节点stage作为输入边界，局部等效梯形渠段反推上游stage；评价基准为Saint-Venant正演结果。",
        font=small,
        fill="#586579",
    )

    left, top, right, bottom = 155, 175, width - 90, 850
    d.rectangle((left, top, right, bottom), outline="#CAD3DF", width=2)
    y_min, y_max = -4.0, 1.0
    for k in range(6):
        y = top + (bottom - top) * k / 5
        v = y_max - (y_max - y_min) * k / 5
        d.line((left, y, right, y), fill="#EEF2F7", width=2)
        d.text((55, y - 13), f"{v:.1f}", font=small, fill="#586579")

    def y_pos(v: float) -> float:
        vv = max(min(v, y_max), y_min)
        return bottom - (bottom - top) * (vv - y_min) / (y_max - y_min)

    zero_y = y_pos(0.0)
    half_y = y_pos(0.5)
    d.line((left, zero_y, right, zero_y), fill="#A7B4C4", width=2)
    d.line((left, half_y, right, half_y), fill="#7B8794", width=2)
    d.text((right - 215, half_y - 30), "NSE=0.5", font=small, fill="#586579")

    n = len(rows)
    group_w = (right - left) / n
    bar_w = group_w * 0.22
    for i, row in enumerate(rows):
        best: Dict[str, float] = row["best_factor"]  # type: ignore[assignment]
        depth_nse = best["depth_nse"]
        q_nse = best["q_nse"]
        cx = left + group_w * (i + 0.5)
        color_h = "#2A9D8F" if depth_nse >= 0.5 else ("#E09F3E" if depth_nse >= 0.0 else "#C75146")
        color_q = "#0B5CAD" if q_nse >= 0.5 else ("#8A6BBE" if q_nse >= 0.0 else "#9AA8B8")
        for offset, val, color, label in [(-bar_w * 0.6, depth_nse, color_h, "h"), (bar_w * 0.6, q_nse, color_q, "Q")]:
            yp = y_pos(val)
            if val >= 0:
                d.rectangle((cx + offset - bar_w / 2, yp, cx + offset + bar_w / 2, zero_y), fill=color)
            else:
                d.rectangle((cx + offset - bar_w / 2, zero_y, cx + offset + bar_w / 2, yp), fill=color)
            d.text((cx + offset - 13, min(yp, zero_y) - 27 if val >= 0 else max(yp, zero_y) + 4), label, font=tiny, fill=color)
        d.text((cx - 46, bottom + 18), str(row["reach"]), font=small, fill="#263241")
        d.text((cx - 42, bottom + 46), f"{float(row['length_m'])/1000:.2f} km", font=tiny, fill="#586579")
        d.text((cx - 44, bottom + 72), str(row["applicability"]), font=tiny, fill=color_h)

    d.text((width / 2 - 175, bottom + 120), "反演方向：下游节点 → 上游节点", font=font, fill="#263241")
    d.text((35, top + 230), "NSE", font=font, fill="#263241")

    legend_x, legend_y = 170, 1010
    legend = [
        ("h NSE（水深反演）", "#2A9D8F"),
        ("Q NSE（流量反演）", "#0B5CAD"),
        ("灰/红表示未达可接受精度", "#9AA8B8"),
    ]
    for label, color in legend:
        d.rectangle((legend_x, legend_y - 12, legend_x + 34, legend_y + 12), fill=color)
        d.text((legend_x + 46, legend_y - 15), label, font=small, fill="#263241")
        legend_x += 380

    d.text(
        (80, height - 70),
        "评价规则：水深和流量NSE均≥0.5为适用；仅水深NSE≥0.5为“仅水深可参考”；NSE<0表示反演结果劣于均值基准。",
        font=small,
        fill="#586579",
    )
    img.save(path, quality=95)


def draw_table_figure(rows: Sequence[Dict[str, object]], path: Path):
    width, height = 1900, 1000
    img = Image.new("RGB", (width, height), "white")
    d = ImageDraw.Draw(img)
    title = base.get_font(40, True)
    font = base.get_font(22)
    small = base.get_font(18)
    d.text((80, 45), "Pati RSR 局部适用性分段评价表", font=title, fill="#162033")
    cols = [
        ("渠段", 120),
        ("长度/km", 120),
        ("S0eq", 135),
        ("b_eq/m", 120),
        ("最佳系数", 120),
        ("h RMSE/m", 135),
        ("h NSE", 115),
        ("Q RMSE", 125),
        ("Q NSE", 115),
        ("结论", 190),
    ]
    x0, y0 = 80, 130
    row_h = 72
    x = x0
    for name, w in cols:
        d.rectangle((x, y0, x + w, y0 + row_h), fill="#F4F7FB", outline="#CAD3DF")
        d.text((x + 10, y0 + 22), name, font=font, fill="#263241")
        x += w
    for r_i, row in enumerate(rows):
        y = y0 + row_h * (r_i + 1)
        best: Dict[str, float] = row["best_factor"]  # type: ignore[assignment]
        vals = [
            row["reach"],
            f"{float(row['length_m'])/1000:.2f}",
            f"{float(row['slope_eq']):.6f}",
            f"{float(row['bottom_width_eq_m']):.1f}",
            f"{best['routing_celerity_factor']:.2f}",
            f"{best['depth_rmse_m']:.3f}",
            f"{best['depth_nse']:.3f}",
            f"{best['q_rmse_m3s']:.2f}",
            f"{best['q_nse']:.3f}",
            row["applicability"],
        ]
        x = x0
        fill = "#FFFFFF" if r_i % 2 == 0 else "#FAFBFD"
        for val, (_, w) in zip(vals, cols):
            d.rectangle((x, y, x + w, y + row_h), fill=fill, outline="#D8E0EA")
            d.text((x + 10, y + 22), str(val), font=small, fill="#263241")
            x += w
    d.text((80, height - 70), "注：Q RMSE单位为m³/s；各段均采用局部等效梯形断面和Saint-Venant正演边界进行评价。", font=small, fill="#586579")
    img.save(path, quality=95)


def write_outputs(rows: Sequence[Dict[str, object]]):
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    csv_path = OUT_DIR / "pati_local_reach_applicability.csv"
    with csv_path.open("w", newline="", encoding="utf-8-sig") as f:
        fields = [
            "reach",
            "downstream_node",
            "upstream_node",
            "length_m",
            "slope_eq",
            "bottom_width_eq_m",
            "side_slope_eq",
            "depth_eq_m",
            "manning_eq",
            "best_factor",
            "depth_rmse_m",
            "depth_nse",
            "q_rmse_m3s",
            "q_nse",
            "depth_peak_time_error_h",
            "q_peak_time_error_h",
            "applicability",
        ]
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            best: Dict[str, float] = row["best_factor"]  # type: ignore[assignment]
            writer.writerow(
                {
                    "reach": row["reach"],
                    "downstream_node": row["downstream_node"],
                    "upstream_node": row["upstream_node"],
                    "length_m": row["length_m"],
                    "slope_eq": row["slope_eq"],
                    "bottom_width_eq_m": row["bottom_width_eq_m"],
                    "side_slope_eq": row["side_slope_eq"],
                    "depth_eq_m": row["depth_eq_m"],
                    "manning_eq": row["manning_eq"],
                    "best_factor": best["routing_celerity_factor"],
                    "depth_rmse_m": best["depth_rmse_m"],
                    "depth_nse": best["depth_nse"],
                    "q_rmse_m3s": best["q_rmse_m3s"],
                    "q_nse": best["q_nse"],
                    "depth_peak_time_error_h": best["depth_peak_time_error_h"],
                    "q_peak_time_error_h": best["q_peak_time_error_h"],
                    "applicability": row["applicability"],
                }
            )
    draw_applicability_figure(rows, FIG_DIR / "fig_pati_local_reach_applicability.png")
    draw_table_figure(rows, FIG_DIR / "fig_pati_local_reach_applicability_table.png")
    summary = {
        "description": "Local equivalent-reach Pati RSR applicability evaluation between diversion/control nodes.",
        "figures": [
            str(FIG_DIR / "fig_pati_local_reach_applicability.png"),
            str(FIG_DIR / "fig_pati_local_reach_applicability_table.png"),
        ],
        "csv": str(csv_path),
        "rows": rows,
    }
    (OUT_DIR / "summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    note = """# Pati RSR 局部适用性分段评价

本图将0-456主干渠按分水口/控制节点划分为若干局部reach。每个reach采用局部等效梯形断面，以Saint-Venant正演得到的下游节点stage作为Pati RSR输入边界，反推上游节点stage和discharge，并与Saint-Venant正演真值对比。

评价结论按NSE划分：水深与流量NSE均不低于0.5时视为“适用”；仅水深NSE不低于0.5时视为“仅水深可参考”；NSE小于0表示反演结果劣于均值基准。

该评价图用于说明Pati RSR在本渠系中更适合作为局部stage反演/方法诊断工具，而不宜直接作为全渠段流量反演主模型。
"""
    (OUT_DIR / "explanation.md").write_text(note, encoding="utf-8")


def run() -> Dict[str, object]:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    forward = base.run_forward_saint_venant(base.ForwardConfig())
    rows = [evaluate_reach(forward, downstream, upstream) for downstream, upstream in REACHES]
    write_outputs(rows)
    return json.loads((OUT_DIR / "summary.json").read_text(encoding="utf-8"))


if __name__ == "__main__":
    result = run()
    print(json.dumps(result, ensure_ascii=False, indent=2))
    print(f"Outputs written to: {OUT_DIR}")
