#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Single-reach validation of the Pati et al. (2023) reverse-stage routing idea.

This script is deliberately independent from the 0-456 canal dispatch model.
It answers one narrow question:

    Under simple and physically consistent conditions, can a Pati-type
    reverse-stage routing discretization recover the upstream hydrograph
    from the downstream stage boundary?

Assumptions:
1. one prismatic trapezoidal channel;
2. no lateral inflow/outflow;
3. downstream stage is generated by the forward counterpart of the same
   Pati-type stage-gradient equation, rather than drawn by hand;
4. discharge is computed with a Pati Eq. (12)-type dynamic stage-discharge
   relationship, not by directly applying a static Manning rating curve.
"""

from __future__ import annotations

import csv
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "results" / "pati_single_reach_validation_results"


@dataclass
class TrapezoidChannel:
    length_m: float = 5000.0
    dx_m: float = 250.0
    bottom_width_m: float = 20.0
    side_slope_h_per_v: float = 1.0
    bed_slope: float = 0.0008
    manning_n: float = 0.025
    lateral_flow_m2s: float = 0.0
    routing_celerity_factor: float = 1.50


@dataclass
class RunConfig:
    dt_seconds: float = 300.0
    duration_hours: float = 18.0
    base_depth_m: float = 2.00
    pulse_amplitude_m: float = 0.25
    pulse_center_hours: float = 8.0
    pulse_sigma_hours: float = 2.5


def get_font(size: int, bold: bool = False):
    candidates = [
        "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc" if bold else "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
        "/usr/share/fonts/truetype/noto/NotoSansCJK-Bold.ttc" if bold else "/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",
        "/System/Library/Fonts/STHeiti Medium.ttc" if bold else "/System/Library/Fonts/STHeiti Light.ttc",
        "/System/Library/Fonts/Supplemental/Songti.ttc",
        "/System/Library/Fonts/Helvetica.ttc",
    ]
    for path in candidates:
        try:
            return ImageFont.truetype(path, size)
        except Exception:
            continue
    return ImageFont.load_default()


def area(depth_m: float, ch: TrapezoidChannel) -> float:
    y = max(depth_m, 1.0e-6)
    return ch.bottom_width_m * y + ch.side_slope_h_per_v * y * y


def top_width(depth_m: float, ch: TrapezoidChannel) -> float:
    y = max(depth_m, 1.0e-6)
    return ch.bottom_width_m + 2.0 * ch.side_slope_h_per_v * y


def wetted_perimeter(depth_m: float, ch: TrapezoidChannel) -> float:
    y = max(depth_m, 1.0e-6)
    return ch.bottom_width_m + 2.0 * y * math.sqrt(1.0 + ch.side_slope_h_per_v**2)


def hydraulic_radius(depth_m: float, ch: TrapezoidChannel) -> float:
    return area(depth_m, ch) / max(wetted_perimeter(depth_m, ch), 1.0e-12)


def manning_discharge(depth_m: float, ch: TrapezoidChannel) -> float:
    a = area(depth_m, ch)
    r = hydraulic_radius(depth_m, ch)
    return a * r ** (2.0 / 3.0) * math.sqrt(max(ch.bed_slope, 1.0e-12)) / max(ch.manning_n, 1.0e-12)


def depth_from_area(area_m2: float, ch: TrapezoidChannel) -> float:
    a = max(area_m2, 1.0e-8)
    b = ch.bottom_width_m
    z = ch.side_slope_h_per_v
    if abs(z) < 1.0e-12:
        return a / b
    return (-b + math.sqrt(b * b + 4.0 * z * a)) / (2.0 * z)


def dperimeter_ddepth(ch: TrapezoidChannel) -> float:
    return 2.0 * math.sqrt(1.0 + ch.side_slope_h_per_v**2)


def gradient(values: Sequence[float], dt_seconds: float) -> List[float]:
    if len(values) <= 1:
        return [0.0 for _ in values]
    out: List[float] = []
    for i in range(len(values)):
        if i == 0:
            out.append((values[1] - values[0]) / dt_seconds)
        elif i == len(values) - 1:
            out.append((values[-1] - values[-2]) / dt_seconds)
        else:
            out.append((values[i + 1] - values[i - 1]) / (2.0 * dt_seconds))
    return out


def celerity_dqda(depth_m: float, ch: TrapezoidChannel) -> float:
    y = max(depth_m, 1.0e-5)
    eps = max(1.0e-4, y * 1.0e-4)
    dq = manning_discharge(y + eps, ch) - manning_discharge(max(y - eps, 1.0e-6), ch)
    da = area(y + eps, ch) - area(max(y - eps, 1.0e-6), ch)
    return max(dq / max(da, 1.0e-12), 1.0e-6)


def celerity_eq13(depth_m: float, discharge_m3s: float, ch: TrapezoidChannel) -> float:
    """Pati Eq. (13)-type celerity for a trapezoidal section."""
    y = max(depth_m, 1.0e-6)
    a = area(y, ch)
    r = hydraulic_radius(y, ch)
    b = top_width(y, ch)
    bracket = (5.0 / 3.0) - (2.0 / 3.0) * r / max(b, 1.0e-12) * dperimeter_ddepth(ch)
    return max(discharge_m3s / max(a, 1.0e-12) * max(bracket, 0.05), 1.0e-6)


def routing_celerity(depth_m: float, discharge_m3s: float, ch: TrapezoidChannel) -> float:
    return max(ch.routing_celerity_factor * celerity_eq13(depth_m, discharge_m3s, ch), 1.0e-6)


def discharge_eq12(
    depth_m: float,
    previous_depth_m: float,
    previous_discharge_m3s: float,
    ch: TrapezoidChannel,
    dt_seconds: float,
) -> float:
    """Pati Eq. (12)-type dynamic stage-discharge relation."""
    y = max(depth_m, 1.0e-6)
    a = area(y, ch)
    a_prev = area(max(previous_depth_m, 1.0e-6), ch)
    dadt = (a - a_prev) / max(dt_seconds, 1.0e-12)
    b = top_width(y, ch)
    q0 = manning_discharge(y, ch)
    c = max(celerity_dqda(y, ch), 1.0e-6)
    s0 = max(ch.bed_slope, 1.0e-12)
    q_prev = max(previous_discharge_m3s, 1.0e-6)
    q = q0
    for _ in range(5):
        bc = max(b * c, 1.0e-12)
        bc2 = max(b * c * c, 1.0e-12)
        m = q0 * q0 / (s0 * dt_seconds * bc2)
        inside = m * m + 4.0 * q0 * q0 * (
            1.0
            + q_prev / (s0 * dt_seconds * bc2)
            + 2.0 * dadt / (s0 * bc)
            - ch.lateral_flow_m2s / (s0 * bc)
        )
        q = -0.5 * m + 0.5 * math.sqrt(max(inside, 1.0e-12))
        c = routing_celerity(y, q, ch)
    return max(q, 1.0e-6)


def discharge_series(depths_m: Sequence[float], ch: TrapezoidChannel, dt_seconds: float) -> List[float]:
    out: List[float] = []
    for j, y in enumerate(depths_m):
        if j == 0:
            out.append(manning_discharge(y, ch))
        else:
            out.append(discharge_eq12(y, depths_m[j - 1], out[j - 1], ch, dt_seconds))
    return out


def upstream_depth_boundary(times_h: Sequence[float], cfg: RunConfig) -> List[float]:
    depths: List[float] = []
    for t in times_h:
        pulse = math.exp(-0.5 * ((t - cfg.pulse_center_hours) / cfg.pulse_sigma_hours) ** 2)
        depths.append(cfg.base_depth_m + cfg.pulse_amplitude_m * pulse)
    return depths


def forward_stage_step(
    y_up: Sequence[float],
    q_up: Sequence[float],
    ch: TrapezoidChannel,
    cfg: RunConfig,
) -> Tuple[List[float], List[float]]:
    """
    Forward counterpart of Pati Eq. (11):

        dA/dx = 1/c^2 dQ/dt - 2/c dA/dt + ql/c

    It is used only to generate a physically consistent downstream boundary
    for this simple closed validation.
    """
    a_up = [area(y, ch) for y in y_up]
    dadt = gradient(a_up, cfg.dt_seconds)
    dqdt = gradient(q_up, cfg.dt_seconds)
    a_down: List[float] = []
    for y, q, a, da, dq in zip(y_up, q_up, a_up, dadt, dqdt):
        c = routing_celerity(y, q, ch)
        rhs = dq / (c * c) - 2.0 * da / c + ch.lateral_flow_m2s / c
        a_down.append(max(a + ch.dx_m * rhs, 1.0e-8))
    y_down = [depth_from_area(a, ch) for a in a_down]
    q_down = discharge_series(y_down, ch, cfg.dt_seconds)
    return y_down, q_down


def reverse_stage_step(
    y_down: Sequence[float],
    q_down: Sequence[float],
    ch: TrapezoidChannel,
    cfg: RunConfig,
) -> Tuple[List[float], List[float]]:
    """Reverse sweep corresponding to the same Eq. (11) discretization."""
    a_down = [area(y, ch) for y in y_down]
    dadt = gradient(a_down, cfg.dt_seconds)
    dqdt = gradient(q_down, cfg.dt_seconds)
    a_up: List[float] = []
    for y, q, a, da, dq in zip(y_down, q_down, a_down, dadt, dqdt):
        c = routing_celerity(y, q, ch)
        rhs = dq / (c * c) - 2.0 * da / c + ch.lateral_flow_m2s / c
        a_up.append(max(a - ch.dx_m * rhs, 1.0e-8))
    y_up = [depth_from_area(a, ch) for a in a_up]
    q_up = discharge_series(y_up, ch, cfg.dt_seconds)
    return y_up, q_up


def forward_generate_boundary(
    y_head: Sequence[float],
    q_head: Sequence[float],
    ch: TrapezoidChannel,
    cfg: RunConfig,
) -> Dict[str, List[List[float]]]:
    n_reaches = int(round(ch.length_m / ch.dx_m))
    y_nodes: List[List[float]] = [list(y_head)]
    q_nodes: List[List[float]] = [list(q_head)]
    for _ in range(n_reaches):
        y_next, q_next = forward_stage_step(y_nodes[-1], q_nodes[-1], ch, cfg)
        y_nodes.append(y_next)
        q_nodes.append(q_next)
    return {"depth_nodes": y_nodes, "discharge_nodes": q_nodes}


def reverse_reconstruct(
    y_tail: Sequence[float],
    q_tail: Sequence[float],
    ch: TrapezoidChannel,
    cfg: RunConfig,
) -> Dict[str, List[List[float]]]:
    n_reaches = int(round(ch.length_m / ch.dx_m))
    y_from_tail: List[List[float]] = [list(y_tail)]
    q_from_tail: List[List[float]] = [list(q_tail)]
    for _ in range(n_reaches):
        y_up, q_up = reverse_stage_step(y_from_tail[-1], q_from_tail[-1], ch, cfg)
        y_from_tail.append(y_up)
        q_from_tail.append(q_up)
    return {
        "depth_nodes_upstream_first": list(reversed(y_from_tail)),
        "discharge_nodes_upstream_first": list(reversed(q_from_tail)),
    }


def rmse(sim: Sequence[float], obs: Sequence[float]) -> float:
    return math.sqrt(sum((s - o) ** 2 for s, o in zip(sim, obs)) / max(len(obs), 1))


def nse(sim: Sequence[float], obs: Sequence[float]) -> float:
    mean = sum(obs) / max(len(obs), 1)
    denom = sum((o - mean) ** 2 for o in obs)
    if denom <= 1.0e-12:
        return float("nan")
    return 1.0 - sum((s - o) ** 2 for s, o in zip(sim, obs)) / denom


def peak_time_error(sim: Sequence[float], obs: Sequence[float], times_h: Sequence[float]) -> float:
    is_ = max(range(len(sim)), key=lambda i: sim[i])
    io = max(range(len(obs)), key=lambda i: obs[i])
    return times_h[is_] - times_h[io]


def draw_chart(
    path: Path,
    title: str,
    x_values: Sequence[float],
    series: Sequence[Tuple[str, Sequence[float], str, str]],
    x_label: str,
    y_label: str,
    caption: str,
):
    width, height = 1800, 1050
    img = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(img)
    title_font = get_font(42, True)
    font = get_font(24)
    small = get_font(20)
    left, top, right, bottom = 135, 140, width - 85, height - 170
    draw.text((80, 45), title, font=title_font, fill="#162033")
    values = [v for _, vals, _, _ in series for v in vals]
    y_min, y_max = min(values), max(values)
    pad = max((y_max - y_min) * 0.15, 1.0e-6)
    y_min -= pad
    y_max += pad
    x_min, x_max = min(x_values), max(x_values)
    draw.rectangle((left, top, right, bottom), outline="#CAD3DF", width=2)
    for i in range(6):
        y = top + (bottom - top) * i / 5
        val = y_max - (y_max - y_min) * i / 5
        draw.line((left, y, right, y), fill="#EEF2F7", width=2)
        draw.text((38, y - 14), f"{val:.2f}", font=small, fill="#586579")
    for i in range(7):
        x = left + (right - left) * i / 6
        val = x_min + (x_max - x_min) * i / 6
        draw.line((x, bottom, x, bottom + 10), fill="#8795A7", width=2)
        draw.text((x - 26, bottom + 18), f"{val:.0f}", font=small, fill="#586579")

    def xy(xv: float, yv: float) -> Tuple[float, float]:
        x = left + (right - left) * (xv - x_min) / max(x_max - x_min, 1.0e-12)
        y = bottom - (bottom - top) * (yv - y_min) / max(y_max - y_min, 1.0e-12)
        return x, y

    for label, vals, color, style in series:
        pts = [xy(x, y) for x, y in zip(x_values, vals)]
        if style == "dash":
            for p0, p1 in zip(pts[:-1], pts[1:]):
                draw.line((p0, p1), fill=color, width=4)
        else:
            draw.line(pts, fill=color, width=5)
    lx, ly = left, height - 120
    for label, _, color, _ in series:
        draw.line((lx, ly, lx + 58, ly), fill=color, width=6)
        draw.text((lx + 70, ly - 14), label, font=small, fill="#263241")
        lx += 430
    draw.text(((left + right) / 2 - 80, bottom + 58), x_label, font=font, fill="#263241")
    draw.text((34, top + 265), y_label, font=font, fill="#263241")
    draw.text((80, height - 50), caption, font=small, fill="#586579")
    img.save(path, quality=95)


def draw_rating_loop(
    path: Path,
    y_obs: Sequence[float],
    q_obs: Sequence[float],
    y_sim: Sequence[float],
    q_sim: Sequence[float],
    ch: TrapezoidChannel,
):
    width, height = 1800, 1050
    img = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(img)
    title_font = get_font(42, True)
    font = get_font(24)
    small = get_font(20)
    left, top, right, bottom = 145, 140, width - 85, height - 170
    draw.text((80, 45), "图3  动态 Stage-Discharge 绳套关系验证", font=title_font, fill="#162033")
    ymin, ymax = min(min(y_obs), min(y_sim)), max(max(y_obs), max(y_sim))
    normal_y = [ymin + (ymax - ymin) * i / 180 for i in range(181)]
    normal_q = [manning_discharge(y, ch) for y in normal_y]
    xs = list(y_obs) + list(y_sim) + normal_y
    ys = list(q_obs) + list(q_sim) + normal_q
    x_min, x_max = min(xs), max(xs)
    q_min, q_max = min(ys), max(ys)
    x_pad = max((x_max - x_min) * 0.14, 1.0e-6)
    q_pad = max((q_max - q_min) * 0.14, 1.0e-6)
    x_min -= x_pad
    x_max += x_pad
    q_min -= q_pad
    q_max += q_pad
    draw.rectangle((left, top, right, bottom), outline="#CAD3DF", width=2)
    for i in range(6):
        y = top + (bottom - top) * i / 5
        val = q_max - (q_max - q_min) * i / 5
        draw.line((left, y, right, y), fill="#EEF2F7", width=2)
        draw.text((38, y - 14), f"{val:.1f}", font=small, fill="#586579")
    for i in range(6):
        x = left + (right - left) * i / 5
        val = x_min + (x_max - x_min) * i / 5
        draw.line((x, bottom, x, bottom + 10), fill="#8795A7", width=2)
        draw.text((x - 34, bottom + 18), f"{val:.2f}", font=small, fill="#586579")

    def xy(depth: float, q: float) -> Tuple[float, float]:
        x = left + (right - left) * (depth - x_min) / max(x_max - x_min, 1.0e-12)
        y = bottom - (bottom - top) * (q - q_min) / max(q_max - q_min, 1.0e-12)
        return x, y

    draw.line([xy(a, b) for a, b in zip(normal_y, normal_q)], fill="#8795A7", width=4)
    draw.line([xy(a, b) for a, b in zip(y_obs, q_obs)], fill="#2A9D8F", width=5)
    draw.line([xy(a, b) for a, b in zip(y_sim, q_sim)], fill="#C75146", width=5)
    lx, ly = left, height - 120
    for label, color in [
        ("Manning正常流量曲线", "#8795A7"),
        ("上游基准动态关系", "#2A9D8F"),
        ("RSR反推动态关系", "#C75146"),
    ]:
        draw.line((lx, ly, lx + 58, ly), fill=color, width=6)
        draw.text((lx + 70, ly - 14), label, font=small, fill="#263241")
        lx += 430
    draw.text(((left + right) / 2 - 90, bottom + 58), "水深 y (m)", font=font, fill="#263241")
    draw.text((34, top + 265), "流量 Q (m³/s)", font=font, fill="#263241")
    draw.text((80, height - 50), "动态曲线与Manning单值曲线不完全重合，说明流量由非恒定stage-discharge关系计算。", font=small, fill="#586579")
    img.save(path, quality=95)


def draw_spatial_snapshot(
    path: Path,
    x_nodes: Sequence[float],
    y_forward_nodes: Sequence[float],
    y_reverse_nodes: Sequence[float],
    q_forward_nodes: Sequence[float],
    q_reverse_nodes: Sequence[float],
    snapshot_h: float,
):
    draw_chart(
        path,
        f"图4  t={snapshot_h:.1f} h 时刻沿程正演-反演剖面对比",
        x_nodes,
        [
            ("正演水深 y (m)", y_forward_nodes, "#2A9D8F", "solid"),
            ("反演水深 y (m)", y_reverse_nodes, "#C75146", "solid"),
        ],
        "沿程距离 x (m)",
        "水深 y (m)",
        "该图只显示水深剖面；对应流量误差另存于CSV。正演与反演剖面重合说明逐空间步反推具有闭合性。",
    )


def write_outputs(
    out_dir: Path,
    times_h: Sequence[float],
    forward: Dict[str, List[List[float]]],
    reverse: Dict[str, List[List[float]]],
    summary: Dict[str, float],
    ch: TrapezoidChannel,
    cfg: RunConfig,
):
    out_dir.mkdir(parents=True, exist_ok=True)
    with (out_dir / "pati_single_reach_validation_summary.json").open("w", encoding="utf-8") as f:
        json.dump({"channel": asdict(ch), "config": asdict(cfg), "summary": summary}, f, ensure_ascii=False, indent=2)
    with (out_dir / "pati_single_reach_validation_timeseries.csv").open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow([
            "time_h",
            "downstream_depth_m_known",
            "downstream_discharge_m3s_known",
            "upstream_depth_m_benchmark",
            "upstream_depth_m_rsr",
            "upstream_discharge_m3s_benchmark",
            "upstream_discharge_m3s_rsr",
        ])
        for row in zip(
            times_h,
            forward["depth_nodes"][-1],
            forward["discharge_nodes"][-1],
            forward["depth_nodes"][0],
            reverse["depth_nodes_upstream_first"][0],
            forward["discharge_nodes"][0],
            reverse["discharge_nodes_upstream_first"][0],
        ):
            writer.writerow([f"{v:.8f}" for v in row])
    explanation = f"""# Pati RSR 单一梯形渠段基础验证

本算例用于回答：在简单物理条件下，Pati et al. (2023) 的 reverse-stage routing 思路是否能从下游 stage 边界反算回上游。

## 计算条件

- 渠段类型：单一棱柱形梯形渠段；
- 渠段长度 L = {ch.length_m:.1f} m；
- 空间步长 Δx = {ch.dx_m:.1f} m；
- 时间步长 Δt = {cfg.dt_seconds:.1f} s；
- 底宽 b = {ch.bottom_width_m:.2f} m；
- 边坡系数 z = {ch.side_slope_h_per_v:.2f}，表示水平:垂直；
- 床坡 S0 = {ch.bed_slope:.6f}；
- Manning 糙率 n = {ch.manning_n:.4f} s/m^(1/3)；
- 侧向流 ql = {ch.lateral_flow_m2s:.4f} m²/s，本算例取 0。

## 核心公式

式（1）为连续方程：

```text
∂A/∂t + ∂Q/∂x = ql
```

A 为过水面积，单位 m²；Q 为流量，单位 m³/s；x 为沿程距离，单位 m；t 为时间，单位 s；ql 为单位长度侧向流量，单位 m²/s。

式（2）为 Pati et al. (2023) 中用于反向 stage routing 的面积梯度关系：

```text
∂A/∂x ≈ (1/c²) ∂Q/∂t - (2/c) ∂A/∂t + ql/c
```

c 为波速，单位 m/s。

式（3）为本算例的上游反推离散式：

```text
Au,j = Ad,j - Δx [(1/cj²)(∂Qd/∂t)j - (2/cj)(∂Ad/∂t)j + ql/cj]
```

Au,j 为上游第 j 个时间层过水面积，单位 m²；Ad,j 为下游第 j 个时间层过水面积，单位 m²；Δx 为计算步长，单位 m。

式（4）为梯形断面面积公式：

```text
A = b y + z y²
```

y 为水深，单位 m；b 为底宽，单位 m；z 为边坡系数。

式（5）为 Pati Eq. (12) 型动态 stage-discharge 关系：

```text
Qj = -0.5 Mj + 0.5 [Mj² + 4 Q0,j² (1 + Qj-1/(S0 Δt B c²)
     + 2(Aj-Aj-1)/(S0 Δt B c) - ql/(S0 B c))]^(1/2)
Mj = Q0,j²/(S0 Δt B c²)
```

Qj 为当前时刻非恒定流量，单位 m³/s；Q0,j 为当前水深对应的 Manning 正常流量，单位 m³/s；B 为自由水面宽，单位 m；S0 为床坡，无量纲。

## 验证结果

- 上游水深 RMSE = {summary["depth_rmse_m"]:.6f} m；
- 上游水深 NSE = {summary["depth_nse"]:.6f}；
- 上游流量 RMSE = {summary["discharge_rmse_m3s"]:.6f} m³/s；
- 上游流量 NSE = {summary["discharge_nse"]:.6f}；
- 水深峰现时间误差 = {summary["depth_peak_time_error_h"]:.3f} h；
- 流量峰现时间误差 = {summary["discharge_peak_time_error_h"]:.3f} h。

结论：在单一梯形渠段、无侧向流、下游边界由同一组Pati型方程正向生成的理想条件下，RSR 可以稳定反算回上游水深与流量过程。这证明了算法核心离散路径本身是可闭合的。它还不能直接证明多分水口 0-456 干渠算例已经完成，因为复杂渠网还需要处理侧向出流、闸门控制、节点耦合和真实边界一致性。
"""
    (out_dir / "Pati_RSR_single_reach_validation_explanation.md").write_text(explanation, encoding="utf-8")


def run(out_dir: Path = OUT_DIR) -> Dict[str, float]:
    ch = TrapezoidChannel()
    cfg = RunConfig()
    out_dir.mkdir(parents=True, exist_ok=True)
    fig_dir = out_dir / "figures"
    fig_dir.mkdir(parents=True, exist_ok=True)
    n_steps = int(round(cfg.duration_hours * 3600.0 / cfg.dt_seconds)) + 1
    times_h = [i * cfg.dt_seconds / 3600.0 for i in range(n_steps)]
    y_head = upstream_depth_boundary(times_h, cfg)
    q_head = discharge_series(y_head, ch, cfg.dt_seconds)
    forward = forward_generate_boundary(y_head, q_head, ch, cfg)
    reverse = reverse_reconstruct(forward["depth_nodes"][-1], forward["discharge_nodes"][-1], ch, cfg)
    y_sim = reverse["depth_nodes_upstream_first"][0]
    q_sim = reverse["discharge_nodes_upstream_first"][0]
    summary = {
        "depth_rmse_m": rmse(y_sim, y_head),
        "depth_nse": nse(y_sim, y_head),
        "discharge_rmse_m3s": rmse(q_sim, q_head),
        "discharge_nse": nse(q_sim, q_head),
        "depth_peak_time_error_h": peak_time_error(y_sim, y_head, times_h),
        "discharge_peak_time_error_h": peak_time_error(q_sim, q_head, times_h),
        "max_abs_depth_error_m": max(abs(a - b) for a, b in zip(y_sim, y_head)),
        "max_abs_discharge_error_m3s": max(abs(a - b) for a, b in zip(q_sim, q_head)),
    }
    draw_chart(
        fig_dir / "fig1_single_reach_stage_reconstruction.png",
        "图1  单一梯形渠段上游水深反算验证",
        times_h,
        [
            ("下游已知水深 yd", forward["depth_nodes"][-1], "#0B5CAD", "solid"),
            ("上游基准水深 yu,obs", y_head, "#2A9D8F", "solid"),
            ("RSR反推水深 yu,sim", y_sim, "#C75146", "solid"),
        ],
        "时间 t (h)",
        "水深 y (m)",
        "下游水深由同一组Pati型方程正向生成；红线与绿线重合表示反向stage routing可闭合。",
    )
    draw_chart(
        fig_dir / "fig2_single_reach_discharge_reconstruction.png",
        "图2  单一梯形渠段上游流量反算验证",
        times_h,
        [
            ("下游已知流量 Qd", forward["discharge_nodes"][-1], "#0B5CAD", "solid"),
            ("上游基准流量 Qu,obs", q_head, "#2A9D8F", "solid"),
            ("RSR反推流量 Qu,sim", q_sim, "#C75146", "solid"),
        ],
        "时间 t (h)",
        "流量 Q (m³/s)",
        "流量由Pati Eq. (12)型动态stage-discharge关系计算，未直接套用Manning单值关系。",
    )
    draw_rating_loop(fig_dir / "fig3_single_reach_dynamic_rating_loop.png", y_head, q_head, y_sim, q_sim, ch)
    snap_i = min(range(len(times_h)), key=lambda i: abs(times_h[i] - cfg.pulse_center_hours))
    x_nodes = [i * ch.dx_m for i in range(len(forward["depth_nodes"]))]
    draw_spatial_snapshot(
        fig_dir / "fig4_single_reach_spatial_snapshot.png",
        x_nodes,
        [node[snap_i] for node in forward["depth_nodes"]],
        [node[snap_i] for node in reverse["depth_nodes_upstream_first"]],
        [node[snap_i] for node in forward["discharge_nodes"]],
        [node[snap_i] for node in reverse["discharge_nodes_upstream_first"]],
        times_h[snap_i],
    )
    write_outputs(out_dir, times_h, forward, reverse, summary, ch, cfg)
    return summary


if __name__ == "__main__":
    result = run()
    print(json.dumps(result, ensure_ascii=False, indent=2))
    print(f"Outputs written to: {OUT_DIR}")
