#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
0-456 real main-canal test without diversion outlets.

Workflow:
1. read the real 0-456 main-canal geometry from input.txt and lineParam.txt;
2. run a forward 1-D Saint-Venant finite-volume model with no diversions;
3. use the downstream stage process generated by the forward model as the
   reverse-stage boundary;
4. sweep from node 456 back to node 0 with a Pati Eq. (11)/(12)-type RSR
   calculation;
5. compare reconstructed head stage/discharge against the Saint-Venant
   forward benchmark.

This is an intermediate validation case. It is harder than the single
trapezoidal channel, but simpler than the full canal with lateral outlets.
"""

from __future__ import annotations

import csv
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

from PIL import Image, ImageDraw, ImageFont

import muskingum_cunge_stage1 as stage1


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data" / "raw"
OUT_DIR = ROOT / "results" / "pati_real_main_canal_no_diversion_results"
FIG_DIR = OUT_DIR / "figures"

G = 9.81
MAIN_START = 0
MAIN_END = 456


@dataclass
class ForwardConfig:
    dt_seconds: float = 1.0
    output_interval_seconds: float = 300.0
    duration_hours: float = 18.0
    base_flow_m3s: float = 60.0
    pulse_amplitude_m3s: float = 20.0
    pulse_center_hours: float = 8.0
    pulse_sigma_hours: float = 2.5
    min_depth_m: float = 0.05
    min_bed_slope: float = 5.0e-5


@dataclass
class RSRConfig:
    routing_celerity_factor: float = 1.50
    min_depth_m: float = 0.05
    min_bed_slope: float = 5.0e-5


def get_font(size: int, bold: bool = False):
    candidates = [
        "/System/Library/Fonts/STHeiti Medium.ttc" if bold else "/System/Library/Fonts/STHeiti Light.ttc",
        "/System/Library/Fonts/Supplemental/Songti.ttc",
        "/System/Library/Fonts/Helvetica.ttc",
    ]
    for path in candidates:
        try:
            return ImageFont.truetype(path, size)
        except Exception:
            continue
    return ImageFont.load_default()


def head_inflow(t_s: float, cfg: ForwardConfig) -> float:
    t_h = t_s / 3600.0
    pulse = math.exp(-0.5 * ((t_h - cfg.pulse_center_hours) / cfg.pulse_sigma_hours) ** 2)
    return cfg.base_flow_m3s + cfg.pulse_amplitude_m3s * pulse


def area_from_depth(h: float, sec: stage1.SectionParam) -> float:
    y = max(h, 0.0)
    return sec.bottom_width * y + sec.side_slope * y * y


def depth_from_area(area: float, sec: stage1.SectionParam) -> float:
    a = max(area, 1.0e-9)
    b = sec.bottom_width
    z = sec.side_slope
    if abs(z) < 1.0e-12:
        return a / max(b, 1.0e-12)
    return (-b + math.sqrt(b * b + 4.0 * z * a)) / (2.0 * z)


def top_width(h: float, sec: stage1.SectionParam) -> float:
    return sec.bottom_width + 2.0 * sec.side_slope * max(h, 0.0)


def wetted_perimeter(h: float, sec: stage1.SectionParam) -> float:
    return sec.bottom_width + 2.0 * max(h, 0.0) * math.sqrt(1.0 + sec.side_slope * sec.side_slope)


def hydraulic_radius(h: float, sec: stage1.SectionParam) -> float:
    return area_from_depth(h, sec) / max(wetted_perimeter(h, sec), 1.0e-12)


def pressure_integral(h: float, sec: stage1.SectionParam) -> float:
    y = max(h, 0.0)
    return 0.5 * sec.bottom_width * y * y + sec.side_slope * y**3 / 3.0


def manning_q(h: float, sec: stage1.SectionParam, slope: float) -> float:
    a = area_from_depth(h, sec)
    r = hydraulic_radius(h, sec)
    return a * r ** (2.0 / 3.0) * math.sqrt(max(slope, 1.0e-8)) / max(sec.manning_n, 1.0e-12)


def normal_depth(q: float, sec: stage1.SectionParam, slope: float, min_depth: float) -> float:
    if q <= 1.0e-9:
        return min_depth
    return max(stage1.normal_depth(q, sec, max(slope, 1.0e-8)), min_depth)


def build_grid():
    nodes = stage1.parse_nodes(DATA_DIR / "input.txt")
    params = stage1.parse_line_params(DATA_DIR / "lineParam.txt")
    ids = [n for n in range(MAIN_START, MAIN_END + 1) if n in nodes]
    x = [0.0]
    for i in range(1, len(ids)):
        x.append(x[-1] + stage1.distance(nodes[ids[i - 1]], nodes[ids[i]]))
    dx_cell: List[float] = []
    for i in range(len(ids)):
        if i == 0:
            dx_cell.append(x[1] - x[0])
        elif i == len(ids) - 1:
            dx_cell.append(x[-1] - x[-2])
        else:
            dx_cell.append(0.5 * (x[i + 1] - x[i - 1]))
    sections = [stage1.section_for_node(node_id, nodes, params) for node_id in ids]
    bed = [nodes[node_id].elev for node_id in ids]
    return ids, x, dx_cell, sections, bed


def local_slope(i: int, x: Sequence[float], bed: Sequence[float], min_slope: float) -> float:
    if i == 0:
        raw = (bed[i] - bed[i + 1]) / max(x[i + 1] - x[i], 1.0)
    elif i == len(bed) - 1:
        raw = (bed[i - 1] - bed[i]) / max(x[i] - x[i - 1], 1.0)
    else:
        raw = (bed[i - 1] - bed[i + 1]) / max(x[i + 1] - x[i - 1], 1.0)
    return max(raw, min_slope)


def wave_speed(area: float, sec: stage1.SectionParam) -> float:
    h = depth_from_area(area, sec)
    hydraulic_depth = area / max(top_width(h, sec), 1.0e-12)
    return math.sqrt(G * max(hydraulic_depth, 1.0e-12))


def flux(area: float, q: float, sec: stage1.SectionParam) -> Tuple[float, float]:
    h = depth_from_area(area, sec)
    return q, q * q / max(area, 1.0e-12) + G * pressure_integral(h, sec)


def hll_flux(
    a_l: float,
    q_l: float,
    sec_l: stage1.SectionParam,
    a_r: float,
    q_r: float,
    sec_r: stage1.SectionParam,
) -> Tuple[float, float]:
    u_l = q_l / max(a_l, 1.0e-12)
    u_r = q_r / max(a_r, 1.0e-12)
    c_l = wave_speed(a_l, sec_l)
    c_r = wave_speed(a_r, sec_r)
    s_l = min(u_l - c_l, u_r - c_r)
    s_r = max(u_l + c_l, u_r + c_r)
    f_l = flux(a_l, q_l, sec_l)
    f_r = flux(a_r, q_r, sec_r)
    if s_l >= 0.0:
        return f_l
    if s_r <= 0.0:
        return f_r
    return (
        (s_r * f_l[0] - s_l * f_r[0] + s_l * s_r * (a_r - a_l)) / (s_r - s_l),
        (s_r * f_l[1] - s_l * f_r[1] + s_l * s_r * (q_r - q_l)) / (s_r - s_l),
    )


def friction_coefficient(area: float, q_reference: float, sec: stage1.SectionParam) -> float:
    h = depth_from_area(area, sec)
    r = area / max(wetted_perimeter(h, sec), 1.0e-12)
    return sec.manning_n**2 * abs(q_reference) / max(area * area * r ** (4.0 / 3.0), 1.0e-12)


def run_forward_saint_venant(cfg: ForwardConfig) -> Dict[str, object]:
    ids, x, dx_cell, sections, bed = build_grid()
    n = len(ids)
    q0 = head_inflow(0.0, cfg)
    a = [
        area_from_depth(normal_depth(q0, sections[i], local_slope(i, x, bed, cfg.min_bed_slope), cfg.min_depth_m), sections[i])
        for i in range(n)
    ]
    q = [q0 for _ in range(n)]
    min_area = [area_from_depth(cfg.min_depth_m, sec) for sec in sections]
    total_steps = int(round(cfg.duration_hours * 3600.0 / cfg.dt_seconds))
    output_every = max(1, int(round(cfg.output_interval_seconds / cfg.dt_seconds)))
    times_h: List[float] = []
    depth_nodes: List[List[float]] = []
    q_nodes: List[List[float]] = []
    water_level_nodes: List[List[float]] = []
    head_q: List[float] = []

    for step in range(total_steps + 1):
        t_s = step * cfg.dt_seconds
        if step % output_every == 0:
            depth = [depth_from_area(max(a[i], min_area[i]), sections[i]) for i in range(n)]
            times_h.append(t_s / 3600.0)
            depth_nodes.append(depth)
            q_nodes.append(list(q))
            water_level_nodes.append([bed[i] + depth[i] for i in range(n)])
            head_q.append(head_inflow(t_s, cfg))
        if step == total_steps:
            break

        q_in = head_inflow(t_s, cfg)
        h_left = normal_depth(q_in, sections[0], local_slope(0, x, bed, cfg.min_bed_slope), cfg.min_depth_m)
        a_left = area_from_depth(h_left, sections[0])
        q_left = q_in
        q_down = max(q[-1], 0.0)
        h_right = normal_depth(q_down, sections[-1], local_slope(n - 1, x, bed, cfg.min_bed_slope), cfg.min_depth_m)
        a_right = area_from_depth(h_right, sections[-1])
        q_right = q[-1]

        fluxes: List[Tuple[float, float]] = [hll_flux(a_left, q_left, sections[0], a[0], q[0], sections[0])]
        for i in range(n - 1):
            fluxes.append(hll_flux(a[i], q[i], sections[i], a[i + 1], q[i + 1], sections[i + 1]))
        fluxes.append(hll_flux(a[-1], q[-1], sections[-1], a_right, q_right, sections[-1]))

        new_a = a[:]
        new_q = q[:]
        for i in range(n):
            dx = max(dx_cell[i], 1.0)
            da = -(fluxes[i + 1][0] - fluxes[i][0]) / dx
            dq = -(fluxes[i + 1][1] - fluxes[i][1]) / dx
            dq += G * max(a[i], min_area[i]) * local_slope(i, x, bed, cfg.min_bed_slope)
            new_a[i] = max(a[i] + cfg.dt_seconds * da, min_area[i])
            new_q[i] = q[i] + cfg.dt_seconds * dq

        for i in range(n):
            cf = friction_coefficient(max(new_a[i], min_area[i]), q[i], sections[i])
            denom = 1.0 + cfg.dt_seconds * G * max(new_a[i], min_area[i]) * cf
            new_q[i] = new_q[i] / max(denom, 1.0e-12)
            c = wave_speed(new_a[i], sections[i])
            q_limit = 8.0 * new_a[i] * max(c, 0.1)
            new_q[i] = max(min(new_q[i], q_limit), -q_limit)
            if abs(new_q[i]) < 1.0e-8:
                new_q[i] = 0.0
        a, q = new_a, new_q

    return {
        "ids": ids,
        "x": x,
        "dx_cell": dx_cell,
        "sections": sections,
        "bed": bed,
        "times_h": times_h,
        "depth_nodes": depth_nodes,
        "water_level_nodes": water_level_nodes,
        "q_nodes": q_nodes,
        "head_q_boundary": head_q,
        "config": asdict(cfg),
    }


def temporal_gradient(values: Sequence[float], dt_seconds: float) -> List[float]:
    if len(values) <= 1:
        return [0.0 for _ in values]
    out: List[float] = []
    for i in range(len(values)):
        if i == 0:
            out.append((values[1] - values[0]) / dt_seconds)
        elif i == len(values) - 1:
            out.append((values[-1] - values[-2]) / dt_seconds)
        else:
            out.append((values[i + 1] - values[i - 1]) / (2.0 * dt_seconds))
    return out


def dperimeter_ddepth(sec: stage1.SectionParam) -> float:
    return 2.0 * math.sqrt(1.0 + sec.side_slope * sec.side_slope)


def celerity_eq13(depth_m: float, discharge_m3s: float, sec: stage1.SectionParam, rsr_cfg: RSRConfig) -> float:
    h = max(depth_m, rsr_cfg.min_depth_m)
    a = area_from_depth(h, sec)
    r = hydraulic_radius(h, sec)
    b = top_width(h, sec)
    bracket = (5.0 / 3.0) - (2.0 / 3.0) * r / max(b, 1.0e-12) * dperimeter_ddepth(sec)
    return max(discharge_m3s / max(a, 1.0e-12) * max(bracket, 0.05), 1.0e-6)


def routing_celerity(depth_m: float, discharge_m3s: float, sec: stage1.SectionParam, rsr_cfg: RSRConfig) -> float:
    return max(rsr_cfg.routing_celerity_factor * celerity_eq13(depth_m, discharge_m3s, sec, rsr_cfg), 1.0e-6)


def celerity_dqda(depth_m: float, sec: stage1.SectionParam, slope: float, rsr_cfg: RSRConfig) -> float:
    h = max(depth_m, rsr_cfg.min_depth_m)
    eps = max(1.0e-4, h * 1.0e-4)
    h0 = max(rsr_cfg.min_depth_m, h - eps)
    h1 = h + eps
    dq = manning_q(h1, sec, slope) - manning_q(h0, sec, slope)
    da = area_from_depth(h1, sec) - area_from_depth(h0, sec)
    return max(dq / max(da, 1.0e-12), 1.0e-6)


def discharge_eq12(
    depth_m: float,
    previous_depth_m: float,
    previous_discharge_m3s: float,
    sec: stage1.SectionParam,
    slope: float,
    dt_seconds: float,
    rsr_cfg: RSRConfig,
) -> float:
    h = max(depth_m, rsr_cfg.min_depth_m)
    h_prev = max(previous_depth_m, rsr_cfg.min_depth_m)
    a = area_from_depth(h, sec)
    a_prev = area_from_depth(h_prev, sec)
    dadt = (a - a_prev) / max(dt_seconds, 1.0e-12)
    b = top_width(h, sec)
    s0 = max(slope, rsr_cfg.min_bed_slope)
    q0 = manning_q(h, sec, s0)
    c = celerity_dqda(h, sec, s0, rsr_cfg)
    q_prev = max(previous_discharge_m3s, 1.0e-6)
    q = q0
    for _ in range(5):
        bc = max(b * c, 1.0e-12)
        bc2 = max(b * c * c, 1.0e-12)
        m = q0 * q0 / (s0 * dt_seconds * bc2)
        inside = m * m + 4.0 * q0 * q0 * (
            1.0 + q_prev / (s0 * dt_seconds * bc2) + 2.0 * dadt / (s0 * bc)
        )
        q = -0.5 * m + 0.5 * math.sqrt(max(inside, 1.0e-12))
        c = routing_celerity(h, q, sec, rsr_cfg)
    return max(q, 1.0e-6)


def discharge_series_from_stage(
    depths: Sequence[float],
    sec: stage1.SectionParam,
    slope: float,
    dt_seconds: float,
    rsr_cfg: RSRConfig,
    initial_q: float | None = None,
) -> List[float]:
    out: List[float] = []
    for j, h in enumerate(depths):
        if j == 0:
            out.append(initial_q if initial_q is not None else manning_q(max(h, rsr_cfg.min_depth_m), sec, slope))
        else:
            out.append(discharge_eq12(h, depths[j - 1], out[j - 1], sec, slope, dt_seconds, rsr_cfg))
    return out


def reverse_stage_routing(forward: Dict[str, object], rsr_cfg: RSRConfig, use_sv_tail_q: bool = True) -> Dict[str, object]:
    ids: List[int] = forward["ids"]  # type: ignore[assignment]
    x: List[float] = forward["x"]  # type: ignore[assignment]
    sections: List[stage1.SectionParam] = forward["sections"]  # type: ignore[assignment]
    bed: List[float] = forward["bed"]  # type: ignore[assignment]
    times_h: List[float] = forward["times_h"]  # type: ignore[assignment]
    depth_nodes_t: List[List[float]] = forward["depth_nodes"]  # type: ignore[assignment]
    q_nodes_t: List[List[float]] = forward["q_nodes"]  # type: ignore[assignment]
    dt = (times_h[1] - times_h[0]) * 3600.0
    n = len(ids)
    tail_depth = [row[-1] for row in depth_nodes_t]
    tail_slope = local_slope(n - 1, x, bed, rsr_cfg.min_bed_slope)
    if use_sv_tail_q:
        current_q = [row[-1] for row in q_nodes_t]
    else:
        current_q = discharge_series_from_stage(tail_depth, sections[-1], tail_slope, dt, rsr_cfg)
    current_depth = tail_depth[:]

    depth_from_tail: List[List[float]] = [current_depth]
    q_from_tail: List[List[float]] = [current_q]
    for i in range(n - 1, 0, -1):
        sec_down = sections[i]
        sec_up = sections[i - 1]
        dx = max(x[i] - x[i - 1], 1.0)
        slope_down = local_slope(i, x, bed, rsr_cfg.min_bed_slope)
        a_down = [area_from_depth(h, sec_down) for h in current_depth]
        dadt = temporal_gradient(a_down, dt)
        dqdt = temporal_gradient(current_q, dt)
        a_up: List[float] = []
        for h, q, a, da, dq in zip(current_depth, current_q, a_down, dadt, dqdt):
            c = routing_celerity(h, q, sec_down, rsr_cfg)
            rhs = dq / (c * c) - 2.0 * da / c
            a_up.append(max(a - dx * rhs, area_from_depth(rsr_cfg.min_depth_m, sec_up)))
        y_up = [depth_from_area(a, sec_up) for a in a_up]
        slope_up = local_slope(i - 1, x, bed, rsr_cfg.min_bed_slope)
        q_up = discharge_series_from_stage(y_up, sec_up, slope_up, dt, rsr_cfg, initial_q=current_q[0])
        depth_from_tail.append(y_up)
        q_from_tail.append(q_up)
        current_depth, current_q = y_up, q_up

    return {
        "depth_nodes_upstream_first": list(reversed(depth_from_tail)),
        "q_nodes_upstream_first": list(reversed(q_from_tail)),
        "use_sv_tail_q": use_sv_tail_q,
        "config": asdict(rsr_cfg),
    }


def rmse(sim: Sequence[float], obs: Sequence[float]) -> float:
    return math.sqrt(sum((s - o) ** 2 for s, o in zip(sim, obs)) / max(len(obs), 1))


def nse(sim: Sequence[float], obs: Sequence[float]) -> float:
    mean = sum(obs) / max(len(obs), 1)
    denom = sum((o - mean) ** 2 for o in obs)
    if denom <= 1.0e-12:
        return float("nan")
    return 1.0 - sum((s - o) ** 2 for s, o in zip(sim, obs)) / denom


def peak_time_error(sim: Sequence[float], obs: Sequence[float], times_h: Sequence[float]) -> float:
    is_ = max(range(len(sim)), key=lambda i: sim[i])
    io = max(range(len(obs)), key=lambda i: obs[i])
    return times_h[is_] - times_h[io]


def draw_two_panel(path: Path, title: str, times_h: Sequence[float], depth_obs, depth_sim, q_obs, q_sim, summary):
    width, height = 1800, 1180
    img = Image.new("RGB", (width, height), "white")
    d = ImageDraw.Draw(img)
    title_font = get_font(42, True)
    font = get_font(24)
    small = get_font(20)
    d.text((80, 45), title, font=title_font, fill="#162033")
    panels = [
        (depth_obs, depth_sim, "渠首水深 h (m)", 140, 515, summary["head_depth_rmse_m"], summary["head_depth_nse"]),
        (q_obs, q_sim, "渠首流量 Q (m³/s)", 650, 1025, summary["head_q_rmse_m3s"], summary["head_q_nse"]),
    ]
    left, right = 140, width - 90
    x_min, x_max = min(times_h), max(times_h)

    def draw_panel(obs, sim, ylabel, top, bottom, err, score):
        vals = list(obs) + list(sim)
        y_min, y_max = min(vals), max(vals)
        pad = max((y_max - y_min) * 0.16, 1.0e-6)
        y_min -= pad
        y_max += pad
        d.rectangle((left, top, right, bottom), outline="#CAD3DF", width=2)
        for k in range(6):
            y = top + (bottom - top) * k / 5
            v = y_max - (y_max - y_min) * k / 5
            d.line((left, y, right, y), fill="#EEF2F7", width=2)
            d.text((45, y - 14), f"{v:.2f}", font=small, fill="#586579")
        for k in range(7):
            x = left + (right - left) * k / 6
            v = x_min + (x_max - x_min) * k / 6
            d.line((x, bottom, x, bottom + 10), fill="#8795A7", width=2)
            d.text((x - 26, bottom + 18), f"{v:.0f}", font=small, fill="#586579")

        def xy(t, v):
            x = left + (right - left) * (t - x_min) / max(x_max - x_min, 1.0e-12)
            y = bottom - (bottom - top) * (v - y_min) / max(y_max - y_min, 1.0e-12)
            return x, y

        d.line([xy(t, v) for t, v in zip(times_h, obs)], fill="#2A9D8F", width=5)
        d.line([xy(t, v) for t, v in zip(times_h, sim)], fill="#C75146", width=4)
        d.text((left + 18, top + 14), f"{ylabel}    RMSE={err:.3f}, NSE={score:.3f}", font=font, fill="#263241")

    for args in panels:
        draw_panel(*args)
    lx, ly = left, height - 95
    for label, color in [("Saint-Venant 正演基准", "#2A9D8F"), ("Pati RSR 反推", "#C75146")]:
        d.line((lx, ly, lx + 58, ly), fill=color, width=6)
        d.text((lx + 70, ly - 14), label, font=small, fill="#263241")
        lx += 360
    d.text((width / 2 - 70, height - 50), "时间 t (h)", font=font, fill="#263241")
    img.save(path, quality=95)


def draw_spatial_error(path: Path, forward: Dict[str, object], reverse: Dict[str, object]):
    ids: List[int] = forward["ids"]  # type: ignore[assignment]
    x: List[float] = forward["x"]  # type: ignore[assignment]
    depth_t: List[List[float]] = forward["depth_nodes"]  # type: ignore[assignment]
    q_t: List[List[float]] = forward["q_nodes"]  # type: ignore[assignment]
    depth_r: List[List[float]] = reverse["depth_nodes_upstream_first"]  # type: ignore[assignment]
    q_r: List[List[float]] = reverse["q_nodes_upstream_first"]  # type: ignore[assignment]
    n = len(ids)
    depth_rmse = []
    q_rmse = []
    for i in range(n):
        obs_h = [row[i] for row in depth_t]
        obs_q = [row[i] for row in q_t]
        depth_rmse.append(rmse(depth_r[i], obs_h))
        q_rmse.append(rmse(q_r[i], obs_q))

    width, height = 1800, 1050
    img = Image.new("RGB", (width, height), "white")
    d = ImageDraw.Draw(img)
    title = get_font(42, True)
    font = get_font(24)
    small = get_font(20)
    d.text((80, 45), "图2  0-456 主干渠 Pati RSR 沿程误差分布", font=title, fill="#162033")
    left, top, right, bottom = 140, 140, width - 90, height - 170
    vals = depth_rmse
    y_min, y_max = 0.0, max(vals) * 1.18
    d.rectangle((left, top, right, bottom), outline="#CAD3DF", width=2)
    for k in range(6):
        y = top + (bottom - top) * k / 5
        v = y_max - (y_max - y_min) * k / 5
        d.line((left, y, right, y), fill="#EEF2F7", width=2)
        d.text((42, y - 14), f"{v:.3f}", font=small, fill="#586579")
    x_min, x_max = min(x), max(x)
    for k in range(7):
        xp = left + (right - left) * k / 6
        v = x_min + (x_max - x_min) * k / 6
        d.line((xp, bottom, xp, bottom + 10), fill="#8795A7", width=2)
        d.text((xp - 34, bottom + 18), f"{v/1000:.1f}", font=small, fill="#586579")

    def xy(xv, yv):
        xp = left + (right - left) * (xv - x_min) / max(x_max - x_min, 1.0e-12)
        yp = bottom - (bottom - top) * (yv - y_min) / max(y_max - y_min, 1.0e-12)
        return xp, yp

    d.line([xy(a, b) for a, b in zip(x, depth_rmse)], fill="#C75146", width=5)
    d.text((left + 18, top + 14), f"最大水深RMSE={max(depth_rmse):.3f} m；渠首流量RMSE={q_rmse[0]:.3f} m³/s", font=font, fill="#263241")
    d.text((width / 2 - 120, bottom + 58), "沿程距离 x (km)", font=font, fill="#263241")
    d.text((30, top + 265), "水深RMSE (m)", font=font, fill="#263241")
    d.text((80, height - 50), "说明：该图用于定位真实非均匀断面上RSR误差沿程放大的位置。", font=small, fill="#586579")
    img.save(path, quality=95)


def write_csv_outputs(forward: Dict[str, object], reverse: Dict[str, object], summary: Dict[str, float]):
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    times_h: List[float] = forward["times_h"]  # type: ignore[assignment]
    depth_t: List[List[float]] = forward["depth_nodes"]  # type: ignore[assignment]
    q_t: List[List[float]] = forward["q_nodes"]  # type: ignore[assignment]
    depth_r: List[List[float]] = reverse["depth_nodes_upstream_first"]  # type: ignore[assignment]
    q_r: List[List[float]] = reverse["q_nodes_upstream_first"]  # type: ignore[assignment]
    with (OUT_DIR / "head_reconstruction_timeseries.csv").open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(["time_h", "h_head_sv_m", "h_head_rsr_m", "q_head_sv_m3s", "q_head_rsr_m3s", "h_tail_sv_m", "q_tail_sv_m3s"])
        for j, t in enumerate(times_h):
            writer.writerow([
                f"{t:.6f}",
                f"{depth_t[j][0]:.8f}",
                f"{depth_r[0][j]:.8f}",
                f"{q_t[j][0]:.8f}",
                f"{q_r[0][j]:.8f}",
                f"{depth_t[j][-1]:.8f}",
                f"{q_t[j][-1]:.8f}",
            ])
    (OUT_DIR / "summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    note = f"""# 0-456真实主干渠无分水口 Pati RSR 测试

本算例使用真实0-456主干渠断面参数和床面高程，先由一维Saint-Venant正演生成下游stage边界，再从456号节点向0号节点执行Pati型reverse stage routing。

## 工况

- 无分水口、无侧向出流；
- 渠首流量为平滑非恒定过程：60 m³/s 基流叠加 20 m³/s 脉冲；
- Saint-Venant 正演时间步长 1 s；
- RSR 输入时间间隔 300 s；
- 真实断面参数来自 input.txt 与 lineParam.txt。

## 结果

- 渠首水深 RMSE = {summary["head_depth_rmse_m"]:.4f} m；
- 渠首水深 NSE = {summary["head_depth_nse"]:.4f}；
- 渠首流量 RMSE = {summary["head_q_rmse_m3s"]:.4f} m³/s；
- 渠首流量 NSE = {summary["head_q_nse"]:.4f}；
- 渠首水深峰现时间误差 = {summary["head_depth_peak_time_error_h"]:.3f} h；
- 渠首流量峰现时间误差 = {summary["head_q_peak_time_error_h"]:.3f} h。

## 解释

这个算例比单一规则梯形渠段更严格，因为沿程断面宽度、渠深、床坡和糙率会变化。若指标明显差于单渠段，不能直接说明Pati方法错误，而更可能说明：真实非均匀断面、Saint-Venant正演边界、Pati扩散波反演假设三者之间存在模型结构差异。
"""
    (OUT_DIR / "explanation.md").write_text(note, encoding="utf-8")


def run() -> Dict[str, float]:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    fcfg = ForwardConfig()
    rcfg = RSRConfig()
    forward = run_forward_saint_venant(fcfg)
    reverse = reverse_stage_routing(forward, rcfg, use_sv_tail_q=True)
    times_h: List[float] = forward["times_h"]  # type: ignore[assignment]
    depth_t: List[List[float]] = forward["depth_nodes"]  # type: ignore[assignment]
    q_t: List[List[float]] = forward["q_nodes"]  # type: ignore[assignment]
    depth_r: List[List[float]] = reverse["depth_nodes_upstream_first"]  # type: ignore[assignment]
    q_r: List[List[float]] = reverse["q_nodes_upstream_first"]  # type: ignore[assignment]
    head_h_obs = [row[0] for row in depth_t]
    head_q_obs = [row[0] for row in q_t]
    summary: Dict[str, float] = {
        "head_depth_rmse_m": rmse(depth_r[0], head_h_obs),
        "head_depth_nse": nse(depth_r[0], head_h_obs),
        "head_q_rmse_m3s": rmse(q_r[0], head_q_obs),
        "head_q_nse": nse(q_r[0], head_q_obs),
        "head_depth_peak_time_error_h": peak_time_error(depth_r[0], head_h_obs, times_h),
        "head_q_peak_time_error_h": peak_time_error(q_r[0], head_q_obs, times_h),
        "max_abs_head_depth_error_m": max(abs(a - b) for a, b in zip(depth_r[0], head_h_obs)),
        "max_abs_head_q_error_m3s": max(abs(a - b) for a, b in zip(q_r[0], head_q_obs)),
        "forward_dt_seconds": fcfg.dt_seconds,
        "rsr_dt_seconds": fcfg.output_interval_seconds,
        "length_m": max(forward["x"]),  # type: ignore[arg-type]
        "node_count": len(forward["ids"]),  # type: ignore[arg-type]
    }
    draw_two_panel(
        FIG_DIR / "fig1_head_reconstruction_sv_vs_pati_rsr.png",
        "图1  0-456真实主干渠无分水口：渠首正演-反演对比",
        times_h,
        head_h_obs,
        depth_r[0],
        head_q_obs,
        q_r[0],
        summary,
    )
    draw_spatial_error(FIG_DIR / "fig2_spatial_reconstruction_error.png", forward, reverse)
    write_csv_outputs(forward, reverse, summary)
    return summary


if __name__ == "__main__":
    result = run()
    print(json.dumps(result, ensure_ascii=False, indent=2))
    print(f"Outputs written to: {OUT_DIR}")
